### GET all clients
GET http://localhost/api/clients

###

### GET concrete client
GET http://localhost/api/clients/13

###

### POST new client
POST http://localhost/api/clients
Content-Type: application/json

{
  "firstName": "Marko",
  "lastName": "Reus",
  "age": 35,
  "email": "markoreus@gmail.com",
  "phone": "+12312441342424",
  "passwordHash": "some_hash",
  "balance": "11213213.00"
}

###

### PATCH client
PATCH http://localhost/api/clients/13
Content-Type: application/json

{
  "balance": "200"
}

###

### DELETE client
DELETE http://localhost/api/clients/12