### GET trainings
GET http://localhost/api/trainers/1/trainings

###

### GET concrete training
GET http://localhost/api/trainers/1/trainings/monday

###

POST http://localhost/api/trainers/1/trainings
Content-Type: application/json

{
  "day_of_week": "monday",
  "start_time": "12:00",
  "duration_minutes": 60
}

###

### PATCH training
PATCH http://localhost/api/trainers/2/trainings/thursday
Content-Type: application/json

{
  "day_of_week": "sunday"
}

###

### DELETE training
DELETE http://localhost/api/trainers/2/trainings/sunday