### GET trainings
GET http://localhost/api/trainers/1/trainings

###

### GET concrete training
GET http://localhost/api/trainers/1/trainings/monday

###

POST http://localhost/api/trainers/1/trainings
Content-Type: application/json

{
  "day_of_week": "friday",
  "start_time": "14:00",
  "duration_minutes": 120
}

###

### PATCH training
PATCH http://localhost/api/trainers/1/trainings/friday
Content-Type: application/json

{
  "day_of_week": "thursday"
}

###

### DELETE training
DELETE http://localhost/api/trainers/1/trainings/thursday