apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      manageAlerts: true
      alertmanagerUid: alertmanager
    isDefault: true
    editable: false
