### GET trainer availabilities
GET http://localhost/api/trainers/2/availabilities

###

### GET concrete trainer availability
GET http://localhost/api/trainers/1/availabilities/monday

###

### GET free slots
GET http://localhost/api/trainers/1/free-slots/monday

###

### POST trainer availability
POST http://localhost/api/trainers/2/availabilities
Content-Type: application/json

{
  "day_of_week": "saturday",
  "start_time": "14:00",
  "end_time": "20:00",
  "duration_minutes": 60
}

###

### PATCH trainer availability
PATCH http://localhost/api/trainers/2/availabilities/saturday
Content-Type: application/json

{
  "start_time": "10:00"
}

###

### DELETE trainer availability
DELETE http://localhost/api/trainers/2/availabilities/saturday