global:
  resolve_timeout: 5m

route:
  receiver: default
  group_by: ['alertname', 'domain', 'severity']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h

receivers:
  - name: default
    webhook_configs:
      - url: '__ALERTMANAGER_WEBHOOK_URL__'
        send_resolved: true
