framework:
    cache:
        app: cache.adapter.redis_tag_aware
        default_redis_provider: '%env(resolve:REDIS_URL)%'
        pools:
            cache.auth_rate_limiter:
                adapter: cache.adapter.redis
            cache.contact_rate_limiter:
                adapter: cache.adapter.redis
