framework:
    cache:
        pools:
            gym.cache:
                adapter: cache.adapter.redis_tag_aware
                provider: 'redis://redis:6379/0'
                default_lifetime: 3600
