doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        mappings:
#            App:
#                type: attribute
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Entity'
                prefix: 'App\User\Entity'
                alias: User
            Admin:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Admin/Entity'
                prefix: 'App\Admin\Entity'
                alias: Admin
            Manager:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Manager/Entity'
                prefix: 'App\Manager\Entity'
                alias: Manager
            Client:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Client/Entity'
                prefix: 'App\Client\Entity'
                alias: Client
            Booking:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Booking/Entity'
                prefix: 'App\Booking\Entity'
                alias: Booking
            Membership:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Membership/Entity'
                prefix: 'App\Membership\Entity'
                alias: Membership
            Payment:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Payment/Entity'
                prefix: 'App\Payment\Entity'
                alias: Payment
            TrainingType:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/TrainingType/Entity'
                prefix: 'App\TrainingType\Entity'
                alias: TrainingType
            Trainer:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Trainer/Entity'
                prefix: 'App\Trainer\Entity'
                alias: Trainer
            TrainerWorkTime:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/TrainerWorkTime/Entity'
                prefix: 'App\TrainerWorkTime\Entity'
                alias: TrainerWorkTime
            Training:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Training/Entity'
                prefix: 'App\Training\Entity'
                alias: Training
            MembershipPlan:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/MembershipPlan/Entity'
                prefix: 'App\MembershipPlan\Entity'
                alias: MembershipPlan
            RefreshToken:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/RefreshToken/Entity'
                prefix: 'App\RefreshToken\Entity'
                alias: RefreshToken
            ImportJob:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/ImportJob/Entity'
                prefix: 'App\ImportJob\Entity'
                alias: ImportJob
            ImportJobItem:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/ImportJobItem/Entity'
                prefix: 'App\ImportJobItem\Entity'
                alias: ImportJobItem
            ImportError:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/ImportError/Entity'
                prefix: 'App\ImportError\Entity'
                alias: ImportError
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
