framework:
    messenger:
        failure_transport: failed

        transports:
            client_outbox:
                dsn: 'doctrine://default'
                options:
                    table_name: messenger_messages
                    queue_name: client_notifications
                    auto_setup: false
                retry_strategy:
                    max_retries: 5
                    delay: 1000
                    multiplier: 2
                    max_delay: 60000


            payment_outbox:
                dsn: 'doctrine://default'
                options:
                    table_name: messenger_messages
                    queue_name: payments
                    auto_setup: false
                retry_strategy:
                    max_retries: 10
                    delay: 1000
                    multiplier: 2
                    max_delay: 60000

            scheduler_default: 'schedule://default'
            scheduler_memberships: 'schedule://memberships'

            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

                options:
                    exchange:
                        name: clients
                        type: direct
                    queues:
                        clients: ~

                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000

            analytics:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: analytics
                        type: direct
                    queues:
                        analytics: ~

                retry_strategy:
                    max_retries: 5
                    delay: 1000
                    multiplier: 2
                    max_delay: 60000

            failed: 'doctrine://default?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_transaction

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            App\ImportJob\Message\ImportMessage: async
            App\ImportJob\Message\SendActivationEmailMessage: client_outbox

            App\Payment\Message\RefundPaymentMessage: payment_outbox
            App\Payment\Message\CancelStripeIntentMessage: payment_outbox

            App\Infrastructure\ClickHouse\Event\AnalyticsEvent: analytics

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
