framework:
    messenger:
        failure_transport: failed

        transports:
            scheduler_memberships: 'doctrine://default'

            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

                options:
                    exchange:
                        name: clients
                        type: direct
                    queues:
                        clients: ~

                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000

            analytics:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: analytics
                        type: direct
                    queues:
                        analytics: ~

                retry_strategy:
                    max_retries: 5
                    delay: 1000
                    multiplier: 2
                    max_delay: 60000

            failed: 'doctrine://default?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            App\ImportJob\Message\ImportMessage: async

            App\Infrastructure\ClickHouse\Event\AnalyticsEvent: analytics

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
