monolog:
    channels:
        - booking
        - payment
        - membership
        - security
        - stripe
        - rabbitmq
        - request
        - deprecation

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]

            stdout:
                type: stream
                path: php://stdout
                level: info
                formatter: monolog.formatter.json
                channels: ['!event', "!doctrine"]

            error:
                type: stream
                path: php://stderr
                level: error
                formatter: monolog.formatter.json

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

#when@test:
#    monolog:
#        handlers:
#            main:
#                type: fingers_crossed
#                action_level: error
#                handler: nested
#                excluded_http_codes: [404, 405]
#                channels: ["!event"]
#            nested:
#                type: stream
#                path: "%kernel.logs_dir%/%kernel.environment%.log"
#                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: stream
                path: php://stdout
                level: info
                formatter: monolog.formatter.json
                channels: ["!event", "!doctrine", "!console", "!booking", "!payment", "!membership", "!security", "!stripe", "!rabbitmq", "!request"]

            error:
                type: stream
                path: php://stderr
                level: error
                formatter: monolog.formatter.json

            booking:
                type: stream
                path: php://stdout
                level: info
                formatter: monolog.formatter.json
                channels: ["booking"]

            payment:
                type: stream
                path: php://stdout
                level: info
                formatter: monolog.formatter.json
                channels: ["payment"]

            membership:
                type: stream
                path: php://stdout
                level: info
                formatter: monolog.formatter.json
                channels: ["membership"]

            security:
                type: stream
                path: php://stdout
                level: info
                formatter: monolog.formatter.json
                channels: ["security"]

            stripe:
                type: stream
                path: php://stdout
                level: info
                formatter: monolog.formatter.json
                channels: ["stripe"]

            rabbitmq:
                type: stream
                path: php://stdout
                level: info
                formatter: monolog.formatter.json
                channels: ["rabbitmq"]

            request:
                type: stream
                path: php://stdout
                level: info
                formatter: monolog.formatter.json
                channels: ["request"]

            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
