framework:
    rate_limiter:
        auth_login_identity:
            policy: sliding_window
            limit: 10
            interval: '15 minutes'
            cache_pool: cache.auth_rate_limiter

        auth_login_ip:
            policy: sliding_window
            limit: 100
            interval: '15 minutes'
            cache_pool: cache.auth_rate_limiter

        auth_refresh_ip:
            policy: sliding_window
            limit: 120
            interval: '1 minute'
            cache_pool: cache.auth_rate_limiter

        auth_activation_ip:
            policy: sliding_window
            limit: 30
            interval: '15 minutes'
            cache_pool: cache.auth_rate_limiter

        auth_registration_burst:
            policy: sliding_window
            limit: 5
            interval: '10 minutes'
            cache_pool: cache.auth_rate_limiter

        auth_registration_hourly:
            policy: sliding_window
            limit: 20
            interval: '1 hour'
            cache_pool: cache.auth_rate_limiter

        auth_registration_ip:
            policy: compound
            limiters:
                - auth_registration_burst
                - auth_registration_hourly

        contact_form_ip:
            policy: sliding_window
            limit: 5
            interval: '15 minutes'
            cache_pool: cache.contact_rate_limiter
