'use client'

import { observer } from "mobx-react-lite";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { AdminShell } from "@/scenes/admin/shared/AdminShell";
import Section, { emptyStateClassName, errorStateClassName, primaryActionClassName, previewCardClassName, secondaryActionClassName } from "@/shared/Section";
import LoadingState from "@/shared/ui/LoadingState";
import { useStore } from "@/store/StoreProvider";
import { formatDate, formatDateTime, formatMoney, formatNullable, humanize, statusClassName } from "@/scenes/admin/shared/admin-format";
import type { AdminTrainerUpdateRequest } from "@/types/admin/admin-trainer.type";
import type { AdminWorktimeCreateRequest } from "@/types/admin/admin-worktime.type";
import type { AdminMembershipPlanUpdateRequest } from "@/types/admin/admin-membership-plan.type";
import type { AdminTrainingTypeUpdateRequest } from "@/types/admin/admin-training-type.type";

const inputClassName = "rounded-md border border-gray-100 bg-gray-20 px-3 py-2 font-normal text-gray-500 transition focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-500/20";

type IdProps = { id: number };

const DetailState = ({ loading, error }: { loading: boolean; error: string | null }) => {
    if (loading) return <LoadingState title="Loading details..." />;
    if (error) return <p className={errorStateClassName} role="alert">{error}</p>;
    return null;
};

export const AdminTrainerDetailsPage = observer(({ id }: IdProps) => {
    const { adminTrainersStore, adminWorktimesStore } = useStore();
    const trainer = adminTrainersStore.selected;
    const { register, handleSubmit } = useForm<AdminTrainerUpdateRequest>();
    const worktimeForm = useForm<AdminWorktimeCreateRequest>();

    useEffect(() => { void adminTrainersStore.loadDetail(id); void adminWorktimesStore.init({ trainerId: id, sort: "date:ASC" }); }, [adminTrainersStore, adminWorktimesStore, id]);

    return <AdminShell title="Trainer details" description="Trainer account plus related worktime intervals.">
        <Section title="Profile">
            <DetailState loading={adminTrainersStore.isDetailLoading} error={adminTrainersStore.detailError} />
            {trainer ? <div className="grid gap-4"><article className={previewCardClassName}><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-bold text-gray-500">{trainer.firstName} {trainer.lastName}</h2><span className={statusClassName(trainer.blockedAt ? "blocked" : trainer.deletedAt ? "deleted" : "active")}>{trainer.blockedAt ? "Blocked" : trainer.deletedAt ? "Deleted" : "Active"}</span></div><p className="break-all text-sm text-gray-600">{trainer.email} · {trainer.phone}</p><p className="mt-2 text-sm text-gray-600">{trainer.trainingType.name} · {formatMoney(trainer.pricePerHour)} · balance {formatMoney(trainer.balance)} · debt {formatMoney(trainer.debt)}</p><p className="mt-2 text-sm text-gray-600">Education: {formatNullable(trainer.education)}</p><p className="text-sm text-gray-600">About: {formatNullable(trainer.about)}</p><p className="break-all text-sm text-gray-600">Photo: {formatNullable(trainer.photoPath)}</p></article>
            <form className="grid gap-3 sm:grid-cols-2" onSubmit={handleSubmit(async (values) => { await adminTrainersStore.update(id, { ...values, pricePerHour: values.pricePerHour ? Number(values.pricePerHour) : undefined }); })}>
                <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">First name<input className={inputClassName} {...register("firstName")} /></label>
                <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Last name<input className={inputClassName} {...register("lastName")} /></label>
                <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Email<input className={inputClassName} type="email" {...register("email")} /></label>
                <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Phone<input className={inputClassName} {...register("phone")} /></label>
                <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Password<input className={inputClassName} type="password" {...register("password")} /></label>
                <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Price per hour<input className={inputClassName} type="number" {...register("pricePerHour")} /></label>
                <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500 sm:col-span-2">Education<textarea className={inputClassName} {...register("education")} /></label>
                <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500 sm:col-span-2">About<textarea className={inputClassName} {...register("about")} /></label>
                <button type="submit" className={primaryActionClassName} disabled={adminTrainersStore.isUpdating}>Save changes</button>
            </form>
            <form className="flex flex-col gap-3 sm:flex-row" onSubmit={(event) => { event.preventDefault(); const file = new FormData(event.currentTarget).get("photo"); if (file instanceof File && file.size > 0) void adminTrainersStore.uploadPhoto(id, file); }}><label className="flex flex-1 flex-col gap-1 text-sm font-semibold text-gray-500">Photo JPEG, PNG or WebP, max 2 MB<input className={inputClassName} type="file" name="photo" accept="image/jpeg,image/png,image/webp" /></label><button type="submit" className={secondaryActionClassName} disabled={adminTrainersStore.isUploadingPhoto}>Upload photo</button></form>
            </div> : null}
        </Section>
        <Section title="Worktime" description="Uses GET /api/worktime/ with trainerId and admin worktime mutations.">
            <form className="mb-5 grid gap-3 sm:grid-cols-4" onSubmit={worktimeForm.handleSubmit(async (values) => { await adminWorktimesStore.createForTrainer(id, values); worktimeForm.reset(); })}>
                <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Date<input className={inputClassName} type="date" {...worktimeForm.register("date", { required: true })} /></label>
                <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Start<input className={inputClassName} type="time" {...worktimeForm.register("startTime", { required: true })} /></label>
                <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">End<input className={inputClassName} type="time" {...worktimeForm.register("endTime", { required: true })} /></label>
                <button type="submit" className={primaryActionClassName} disabled={adminWorktimesStore.isCreating}>Add</button>
            </form>
            {adminWorktimesStore.error ? <p className={errorStateClassName} role="alert">{adminWorktimesStore.error}</p> : null}
            {adminWorktimesStore.items.length === 0 ? <p className={emptyStateClassName}>No worktime records for this trainer.</p> : <div className="grid gap-3">{adminWorktimesStore.items.map((item) => <article key={item.id} className={previewCardClassName}><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold text-gray-500">{formatDate(item.date)}</h3><p className="text-sm text-gray-600">Free slots: {item.freeSlots.length}</p></div><button type="button" className={secondaryActionClassName} onClick={() => void adminWorktimesStore.delete(item.id)}>Delete</button></div></article>)}</div>}
        </Section>
    </AdminShell>;
});

export const AdminBookingDetailsPage = observer(({ id }: IdProps) => { const { adminBookingsStore } = useStore(); useEffect(() => { void adminBookingsStore.loadDetail(id); }, [adminBookingsStore, id]); const booking = adminBookingsStore.selected; return <AdminShell title="Booking details"><Section title={`Booking #${id}`}><DetailState loading={adminBookingsStore.isDetailLoading} error={adminBookingsStore.detailError} />{booking ? <article className={previewCardClassName}><span className={statusClassName(booking.status)}>{humanize(booking.status)}</span><p className="mt-3 text-sm text-gray-600">Client #{booking.clientId} · Trainer #{booking.trainerId} · {formatDate(booking.date)} {booking.startTime} · {booking.durationMinutes} min</p><p className="text-sm text-gray-600">Booked {formatDateTime(booking.bookedAt)}</p><p className="text-sm text-gray-600">Payment {formatMoney(booking.payment.amount, booking.payment.currency)} · {humanize(booking.payment.status)}</p><button type="button" className={`${secondaryActionClassName} mt-4`} onClick={() => void adminBookingsStore.cancel(id)}>Cancel booking</button></article> : null}</Section></AdminShell>; });

export const AdminMembershipDetailsPage = observer(({ id }: IdProps) => { const { adminMembershipsStore } = useStore(); useEffect(() => { void adminMembershipsStore.loadDetail(id); }, [adminMembershipsStore, id]); const membership = adminMembershipsStore.selected; return <AdminShell title="Membership details"><Section title={`Membership #${id}`}><DetailState loading={adminMembershipsStore.isDetailLoading} error={adminMembershipsStore.detailError} />{membership ? <article className={previewCardClassName}><span className={statusClassName(membership.status)}>{humanize(membership.status)}</span><p className="mt-3 text-sm text-gray-600">{membership.name} · plan {membership.membershipPlan?.name ?? "custom"}</p><p className="text-sm text-gray-600">{formatDate(membership.startDate)} - {formatDate(membership.endDate)} · visits {membership.visits}/{membership.sessionLimit ?? "unlimited"}</p><p className="text-sm text-gray-600">Payment {formatMoney(membership.payment.amount, membership.payment.currency)} · {humanize(membership.payment.status)}</p><div className="mt-4 flex flex-wrap gap-2">{["cancel", "freeze", "unfreeze", "renew", "terminate"].map((action) => <button key={action} type="button" className={secondaryActionClassName} onClick={() => void adminMembershipsStore[action as "cancel" | "freeze" | "unfreeze" | "renew" | "terminate"](id)}>{humanize(action)}</button>)}</div></article> : null}</Section></AdminShell>; });

export const AdminMembershipPlanDetailsPage = observer(({ id }: IdProps) => { const { adminMembershipPlansStore } = useStore(); const { register, handleSubmit } = useForm<AdminMembershipPlanUpdateRequest>(); useEffect(() => { void adminMembershipPlansStore.loadDetail(id); }, [adminMembershipPlansStore, id]); const plan = adminMembershipPlansStore.selected; return <AdminShell title="Tariff plan details"><Section title={`Plan #${id}`}><DetailState loading={adminMembershipPlansStore.isDetailLoading} error={adminMembershipPlansStore.detailError} />{plan ? <><article className={previewCardClassName}><h2 className="text-lg font-bold text-gray-500">{plan.name}</h2><p className="text-sm text-gray-600">{formatMoney(plan.price)} · {plan.durationDays} days · {plan.sessionLimit ?? "unlimited"} sessions</p></article><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={handleSubmit(async (values) => { await adminMembershipPlansStore.update(id, { ...values, durationDays: values.durationDays ? Number(values.durationDays) : undefined, sessionLimit: values.sessionLimit ? Number(values.sessionLimit) : undefined, price: values.price ? Number(values.price) : undefined }); })}><label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Name<input className={inputClassName} {...register("name")} /></label><label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Duration<input className={inputClassName} type="number" {...register("durationDays")} /></label><label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Session limit<input className={inputClassName} type="number" {...register("sessionLimit")} /></label><label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Price cents<input className={inputClassName} type="number" {...register("price")} /></label><button type="submit" className={primaryActionClassName}>Save</button></form></> : null}</Section></AdminShell>; });

export const AdminPaymentDetailsPage = observer(({ id }: IdProps) => { const { adminPaymentsStore } = useStore(); useEffect(() => { void adminPaymentsStore.loadDetail(id); }, [adminPaymentsStore, id]); const payment = adminPaymentsStore.selected; return <AdminShell title="Payment details"><Section title={`Payment #${id}`}><DetailState loading={adminPaymentsStore.isDetailLoading} error={adminPaymentsStore.detailError} />{payment ? <article className={previewCardClassName}><span className={statusClassName(payment.status)}>{humanize(payment.status)}</span><p className="mt-3 text-sm text-gray-600">{formatMoney(payment.amount, payment.currency)} · {humanize(payment.category)} · {humanize(payment.method)} · refund {payment.isRefund ? "yes" : "no"}</p><p className="break-all text-sm text-gray-600">Stripe intent: {formatNullable(payment.stripePaymentIntentId)}</p><p className="text-sm text-gray-600">Created {formatDateTime(payment.createdAt)} · paid {formatDateTime(payment.paidAt)} · expires {formatDateTime(payment.expiresAt)}</p></article> : null}</Section></AdminShell>; });

export const AdminTrainingTypeDetailsPage = observer(({ id }: IdProps) => { const { adminTrainingTypesStore } = useStore(); const { register, handleSubmit } = useForm<AdminTrainingTypeUpdateRequest>(); useEffect(() => { void adminTrainingTypesStore.loadDetail(id); }, [adminTrainingTypesStore, id]); const type = adminTrainingTypesStore.selected; return <AdminShell title="Training type details"><Section title={`Training type #${id}`}><DetailState loading={adminTrainingTypesStore.isDetailLoading} error={adminTrainingTypesStore.detailError} />{type ? <><article className={previewCardClassName}><h2 className="text-lg font-bold text-gray-500">{type.name}</h2><p className="text-sm text-gray-600">{type.description}</p><p className="break-all text-sm text-gray-600">Image: {formatNullable(type.photoPath)}</p></article><form className="mt-4 grid gap-3" onSubmit={handleSubmit(async (values) => { await adminTrainingTypesStore.update(id, values); })}><label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Name<input className={inputClassName} {...register("name")} /></label><label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Description<textarea className={inputClassName} {...register("description")} /></label><button type="submit" className={primaryActionClassName}>Save</button></form><form className="mt-4 flex flex-col gap-3 sm:flex-row" onSubmit={(event) => { event.preventDefault(); const file = new FormData(event.currentTarget).get("photo"); if (file instanceof File && file.size > 0) void adminTrainingTypesStore.uploadPhoto(id, file); }}><label className="flex flex-1 flex-col gap-1 text-sm font-semibold text-gray-500">Image JPEG, PNG or WebP, max 2 MB<input className={inputClassName} type="file" name="photo" accept="image/jpeg,image/png,image/webp" /></label><button type="submit" className={secondaryActionClassName}>Upload image</button></form></> : null}</Section></AdminShell>; });
