'use client'

import Link from "next/link";
import { useForm } from "react-hook-form";
import { AdminShell } from "@/scenes/admin/shared/AdminShell";
import AdminResourcePage from "@/scenes/admin/shared/AdminResourcePage";
import { formatDate, formatDateTime, formatMoney, formatNullable, humanize, statusClassName } from "@/scenes/admin/shared/admin-format";
import { primaryActionClassName, secondaryActionClassName } from "@/shared/Section";
import { useStore } from "@/store/StoreProvider";
import { parseAdminTrainersListParams, DEFAULT_ADMIN_TRAINERS_SORT } from "@/api/admin/trainers.api";
import { parseAdminBookingsListParams, DEFAULT_ADMIN_BOOKINGS_SORT } from "@/api/admin/bookings.api";
import { parseAdminMembershipsListParams, DEFAULT_ADMIN_MEMBERSHIPS_SORT } from "@/api/admin/memberships.api";
import { parseAdminMembershipPlansListParams } from "@/api/admin/membership-plans.api";
import { DEFAULT_MEMBERSHIP_PLANS_SORT } from "@/api/public/membership-plans.api";
import { parseAdminPaymentsListParams, DEFAULT_ADMIN_PAYMENTS_SORT } from "@/api/admin/payments.api";
import { parseAdminTrainingTypesListParams } from "@/api/admin/training-types.api";
import { DEFAULT_TRAINING_TYPES_SORT } from "@/api/public/training-types.api";
import { parseAdminTrainingsListParams, DEFAULT_ADMIN_TRAININGS_SORT } from "@/api/admin/trainings.api";
import { BookingStatusEnum } from "@/types/booking/bookings-status.enum";
import { MembershipStatusEnum } from "@/types/membership/membership-status.enum";
import { PaymentStatusEnum } from "@/types/payment/payment-status.enum";
import type { AdminTrainerCreateRequest } from "@/types/admin/admin-trainer.type";
import type { AdminMembershipPlanCreateRequest } from "@/types/admin/admin-membership-plan.type";
import type { AdminTrainingTypeCreateRequest } from "@/types/admin/admin-training-type.type";

const boolOptions = [{ label: "Yes", value: "true" }, { label: "No", value: "false" }];
const bookingStatusOptions = Object.values(BookingStatusEnum).map((value) => ({ label: humanize(value), value }));
const membershipStatusOptions = Object.values(MembershipStatusEnum).map((value) => ({ label: humanize(value), value }));
const paymentStatusOptions = Object.values(PaymentStatusEnum).map((value) => ({ label: humanize(value), value }));
const inputClassName = "rounded-md border border-gray-100 bg-gray-20 px-3 py-2 font-normal text-gray-500 transition focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-500/20";

const AdminTrainerCreateForm = () => {
    const { adminTrainersStore } = useStore();
    const { register, handleSubmit, reset, formState: { errors } } = useForm<AdminTrainerCreateRequest>();

    return (
        <form className="grid gap-3 sm:grid-cols-2" onSubmit={handleSubmit(async (values) => {
            await adminTrainersStore.create({ ...values, trainingTypeId: Number(values.trainingTypeId), pricePerHour: Number(values.pricePerHour) });
            reset();
        })}>
            {[["firstName", "First name"], ["lastName", "Last name"], ["email", "Email"], ["phone", "Phone"], ["password", "Password"], ["trainingTypeId", "Training type ID"], ["pricePerHour", "Price per hour"]].map(([name, label]) => (
                <label key={name} className="flex flex-col gap-1 text-sm font-semibold text-gray-500">{label}<input className={inputClassName} type={name.includes("Id") || name === "pricePerHour" ? "number" : name === "password" ? "password" : "text"} {...register(name as keyof AdminTrainerCreateRequest, { required: `${label} is required` })} />{errors[name as keyof AdminTrainerCreateRequest] ? <span className="font-normal text-primary-500">Required</span> : null}</label>
            ))}
            <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500 sm:col-span-2">Education<textarea className={inputClassName} {...register("education")} /></label>
            <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500 sm:col-span-2">About<textarea className={inputClassName} {...register("about")} /></label>
            <button type="submit" className={primaryActionClassName} disabled={adminTrainersStore.isCreating}>{adminTrainersStore.isCreating ? "Creating..." : "Create trainer"}</button>
        </form>
    );
};

const AdminPlanCreateForm = () => {
    const { adminMembershipPlansStore } = useStore();
    const { register, handleSubmit, reset } = useForm<AdminMembershipPlanCreateRequest>();
    return <form className="grid gap-3 sm:grid-cols-2" onSubmit={handleSubmit(async (values) => { await adminMembershipPlansStore.create({ ...values, durationDays: Number(values.durationDays), sessionLimit: values.sessionLimit === null || values.sessionLimit === undefined ? null : Number(values.sessionLimit), price: Number(values.price) }); reset(); })}>
        <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Name<input className={inputClassName} {...register("name", { required: true })} /></label>
        <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Duration days<input className={inputClassName} type="number" {...register("durationDays", { required: true })} /></label>
        <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Session limit<input className={inputClassName} type="number" {...register("sessionLimit")} /></label>
        <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Price cents<input className={inputClassName} type="number" {...register("price", { required: true })} /></label>
        <button type="submit" className={primaryActionClassName} disabled={adminMembershipPlansStore.isCreating}>{adminMembershipPlansStore.isCreating ? "Creating..." : "Create plan"}</button>
    </form>;
};

const AdminTrainingTypeCreateForm = () => {
    const { adminTrainingTypesStore } = useStore();
    const { register, handleSubmit, reset } = useForm<AdminTrainingTypeCreateRequest>();
    return <form className="grid gap-3" onSubmit={handleSubmit(async (values) => { await adminTrainingTypesStore.create(values); reset(); })}>
        <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Name<input className={inputClassName} {...register("name", { required: true })} /></label>
        <label className="flex flex-col gap-1 text-sm font-semibold text-gray-500">Description<textarea className={inputClassName} {...register("description", { required: true })} /></label>
        <button type="submit" className={primaryActionClassName} disabled={adminTrainingTypesStore.isCreating}>{adminTrainingTypesStore.isCreating ? "Creating..." : "Create type"}</button>
    </form>;
};

export const AdminTrainersPage = () => {
    const { adminTrainersStore } = useStore();
    return <AdminShell title="Trainers" description="Manage trainer accounts, status and photos."><AdminResourcePage
        title="Trainer list" description="Uses GET /api/admin/trainers/ and trainer account mutations."
        store={adminTrainersStore} parseParams={parseAdminTrainersListParams} defaultSort={DEFAULT_ADMIN_TRAINERS_SORT}
        renderCreate={<AdminTrainerCreateForm />}
        filters={[{ name: "minPricePerHour", label: "Min price", type: "number" }, { name: "maxPricePerHour", label: "Max price", type: "number" }, { name: "trainingTypeId", label: "Training type ID", type: "number" }, { name: "minBalance", label: "Min balance", type: "number" }, { name: "maxBalance", label: "Max balance", type: "number" }, { name: "isDeleted", label: "Deleted", type: "select", options: boolOptions }, { name: "isBlocked", label: "Blocked", type: "select", options: boolOptions }]}
        sortOptions={["lastName:ASC", "firstName:ASC", "pricePerHour:ASC", "pricePerHour:DESC", "balance:DESC"].map((value) => ({ label: value, value }))}
        renderItem={(trainer) => <div className="space-y-2"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-bold text-gray-500">{trainer.firstName} {trainer.lastName}</h3><p className="break-all text-sm text-gray-600">{trainer.email} · {trainer.phone}</p></div><span className={statusClassName(trainer.blockedAt ? "blocked" : trainer.deletedAt ? "deleted" : "active")}>{trainer.blockedAt ? "Blocked" : trainer.deletedAt ? "Deleted" : "Active"}</span></div><p className="text-sm text-gray-600">{trainer.trainingType.name} · {formatMoney(trainer.pricePerHour)} / hour · balance {formatMoney(trainer.balance)} · debt {formatMoney(trainer.debt)}</p><Link className={secondaryActionClassName} href={`/admin/trainers/${trainer.id}`}>Details</Link></div>}
        getActions={(trainer) => [{ key: "delete", label: "Delete", description: "Soft delete this trainer.", tone: "danger", run: () => adminTrainersStore.delete(trainer.id) }, { key: "restore", label: "Restore", description: "Restore this trainer.", run: () => adminTrainersStore.restore(trainer.id) }, { key: "block", label: "Block", description: "Block this trainer account.", tone: "danger", run: () => adminTrainersStore.block(trainer.id) }, { key: "unblock", label: "Unblock", description: "Unblock this trainer account.", run: () => adminTrainersStore.unblock(trainer.id) }]}
    /></AdminShell>;
};

export const AdminBookingsPage = () => { const { adminBookingsStore } = useStore(); return <AdminShell title="Bookings" description="Search bookings and cancel when allowed by backend."><AdminResourcePage title="Booking list" description="Uses GET /api/bookings/." store={adminBookingsStore} parseParams={parseAdminBookingsListParams} defaultSort={DEFAULT_ADMIN_BOOKINGS_SORT} filters={[{ name: "trainerId", label: "Trainer ID", type: "number" }, { name: "clientId", label: "Client ID", type: "number" }, { name: "status", label: "Status", type: "select", options: bookingStatusOptions }, { name: "date", label: "Date", type: "date" }, { name: "startTime", label: "Start time", type: "time" }, { name: "durationMinutes", label: "Duration", type: "number" }]} sortOptions={["date:ASC", "date:DESC", "bookedAt:DESC", "status:ASC"].map((value) => ({ label: value, value }))} renderItem={(booking) => <div className="space-y-2"><div className="flex flex-wrap justify-between gap-3"><h3 className="text-lg font-bold text-gray-500">Booking #{booking.id}</h3><span className={statusClassName(booking.status)}>{humanize(booking.status)}</span></div><p className="text-sm text-gray-600">Client #{booking.clientId} · Trainer #{booking.trainerId} · {formatDate(booking.date)} {booking.startTime} · {booking.durationMinutes} min</p><p className="text-sm text-gray-600">Payment {formatMoney(booking.payment.amount, booking.payment.currency)} · {humanize(booking.payment.status)}</p><Link className={secondaryActionClassName} href={`/admin/bookings/${booking.id}`}>Details</Link></div>} getActions={(booking) => [{ key: "cancel", label: "Cancel", description: "Cancel this booking through backend cancellation service.", tone: "danger", run: () => adminBookingsStore.cancel(booking.id) }]} /></AdminShell>; };

export const AdminMembershipsPage = () => { const { adminMembershipsStore } = useStore(); return <AdminShell title="Client memberships" description="Manage client membership lifecycle."><AdminResourcePage title="Membership list" description="Uses GET /api/memberships/." store={adminMembershipsStore} parseParams={parseAdminMembershipsListParams} defaultSort={DEFAULT_ADMIN_MEMBERSHIPS_SORT} filters={[{ name: "membershipPlanId", label: "Plan ID", type: "number" }, { name: "clientId", label: "Client ID", type: "number" }, { name: "status", label: "Status", type: "select", options: membershipStatusOptions }, { name: "minVisits", label: "Min visits", type: "number" }, { name: "maxVisits", label: "Max visits", type: "number" }]} sortOptions={["startDate:ASC", "startDate:DESC", "endDate:ASC", "visits:DESC", "status:ASC"].map((value) => ({ label: value, value }))} renderItem={(membership) => <div className="space-y-2"><div className="flex flex-wrap justify-between gap-3"><h3 className="text-lg font-bold text-gray-500">{membership.name} #{membership.id}</h3><span className={statusClassName(membership.status)}>{humanize(membership.status)}</span></div><p className="text-sm text-gray-600">Plan {membership.membershipPlan?.name ?? "custom"} · visits {membership.visits}/{membership.sessionLimit ?? "unlimited"} · {formatDate(membership.startDate)} - {formatDate(membership.endDate)}</p><p className="text-sm text-gray-600">Payment {formatMoney(membership.payment.amount, membership.payment.currency)} · {humanize(membership.payment.status)}</p><Link className={secondaryActionClassName} href={`/admin/memberships/${membership.id}`}>Details</Link></div>} getActions={(membership) => ["cancel", "freeze", "unfreeze", "renew", "terminate"].map((action) => ({ key: action, label: humanize(action), description: `${humanize(action)} membership #${membership.id}.`, tone: action === "terminate" || action === "cancel" ? "danger" as const : "default" as const, run: () => adminMembershipsStore[action as "cancel" | "freeze" | "unfreeze" | "renew" | "terminate"](membership.id) }))} /></AdminShell>; };

export const AdminMembershipPlansPage = () => { const { adminMembershipPlansStore } = useStore(); return <AdminShell title="Tariff plans" description="Create and maintain membership plans."><AdminResourcePage title="Plan list" description="Reads via public GET and mutates through admin endpoints." store={adminMembershipPlansStore} parseParams={parseAdminMembershipPlansListParams} defaultSort={DEFAULT_MEMBERSHIP_PLANS_SORT} renderCreate={<AdminPlanCreateForm />} filters={[{ name: "minDurationDays", label: "Min duration", type: "number" }, { name: "maxDurationDays", label: "Max duration", type: "number" }, { name: "minSessionLimit", label: "Min sessions", type: "number" }, { name: "maxSessionLimit", label: "Max sessions", type: "number" }, { name: "minPrice", label: "Min price", type: "number" }, { name: "maxPrice", label: "Max price", type: "number" }, { name: "isUnlimited", label: "Unlimited", type: "select", options: boolOptions }]} sortOptions={["price:ASC", "price:DESC", "durationDays:ASC", "sessionLimit:DESC"].map((value) => ({ label: value, value }))} renderItem={(plan) => <div className="space-y-2"><h3 className="text-lg font-bold text-gray-500">{plan.name}</h3><p className="text-sm text-gray-600">{formatMoney(plan.price)} · {plan.durationDays} days · {plan.sessionLimit ?? "unlimited"} sessions</p><Link className={secondaryActionClassName} href={`/admin/membership-plans/${plan.id}`}>Details</Link></div>} getActions={(plan) => [{ key: "delete", label: "Delete", description: "Delete this plan. Backend may return 409 when it is used by memberships.", tone: "danger", run: () => adminMembershipPlansStore.delete(plan.id) }]} /></AdminShell>; };

export const AdminPaymentsPage = () => { const { adminPaymentsStore } = useStore(); return <AdminShell title="Payments" description="Read-only payment ledger."><AdminResourcePage title="Payment list" description="Uses GET /api/payments/." store={adminPaymentsStore} parseParams={parseAdminPaymentsListParams} defaultSort={DEFAULT_ADMIN_PAYMENTS_SORT} filters={[{ name: "trainerId", label: "Trainer ID", type: "number" }, { name: "clientId", label: "Client ID", type: "number" }, { name: "minAmount", label: "Min amount", type: "number" }, { name: "maxAmount", label: "Max amount", type: "number" }, { name: "isRefund", label: "Refund", type: "select", options: boolOptions }, { name: "status", label: "Status", type: "select", options: paymentStatusOptions }, { name: "minCreatedAt", label: "Created after", type: "datetime-local" }, { name: "maxCreatedAt", label: "Created before", type: "datetime-local" }]} sortOptions={["createdAt:DESC", "createdAt:ASC", "amount:DESC", "status:ASC", "isRefund:DESC"].map((value) => ({ label: value, value }))} renderItem={(payment) => <div className="space-y-2"><div className="flex flex-wrap justify-between gap-3"><h3 className="text-lg font-bold text-gray-500">Payment #{payment.id}</h3><span className={statusClassName(payment.status)}>{humanize(payment.status)}</span></div><p className="text-sm text-gray-600">{formatMoney(payment.amount, payment.currency)} · {humanize(payment.category)} · {humanize(payment.method)} · refund: {payment.isRefund ? "yes" : "no"}</p><p className="break-all text-sm text-gray-600">Stripe intent: {formatNullable(payment.stripePaymentIntentId)} · created {formatDateTime(payment.createdAt)}</p><Link className={secondaryActionClassName} href={`/admin/payments/${payment.id}`}>Details</Link></div>} /></AdminShell>; };

export const AdminTrainingTypesPage = () => { const { adminTrainingTypesStore } = useStore(); return <AdminShell title="Training types" description="Manage public training type catalog."><AdminResourcePage title="Training type list" description="Reads via public GET and mutates through admin endpoints." store={adminTrainingTypesStore} parseParams={parseAdminTrainingTypesListParams} defaultSort={DEFAULT_TRAINING_TYPES_SORT} renderCreate={<AdminTrainingTypeCreateForm />} filters={[]} sortOptions={["name:ASC", "name:DESC"].map((value) => ({ label: value, value }))} renderItem={(type) => <div className="space-y-2"><h3 className="text-lg font-bold text-gray-500">{type.name}</h3><p className="text-sm text-gray-600">{type.description}</p><p className="break-all text-sm text-gray-600">Image: {formatNullable(type.photoPath)}</p><Link className={secondaryActionClassName} href={`/admin/training-types/${type.id}`}>Details</Link></div>} getActions={(type) => [{ key: "delete", label: "Delete", description: "Delete this training type.", tone: "danger", run: () => adminTrainingTypesStore.delete(type.id) }]} /></AdminShell>; };

export const AdminTrainingsPage = () => { const { adminTrainingsStore } = useStore(); return <AdminShell title="Trainings" description="Manage training schedule state. No admin detail GET exists in backend."><AdminResourcePage title="Training list" description="Uses GET /api/admin/trainings/." store={adminTrainingsStore} parseParams={parseAdminTrainingsListParams} defaultSort={DEFAULT_ADMIN_TRAININGS_SORT} filters={[{ name: "trainerId", label: "Trainer ID", type: "number" }, { name: "clientId", label: "Client ID", type: "number" }, { name: "status", label: "Status", type: "select", options: bookingStatusOptions }, { name: "date", label: "Date", type: "date" }, { name: "startTime", label: "Start time", type: "time" }, { name: "durationMinutes", label: "Duration", type: "number" }, { name: "isBusy", label: "Busy", type: "select", options: boolOptions }]} sortOptions={["startTime:ASC", "date:ASC", "bookedAt:DESC", "status:ASC", "isBusy:DESC"].map((value) => ({ label: value, value }))} renderItem={(training) => <div className="space-y-2"><div className="flex flex-wrap justify-between gap-3"><h3 className="text-lg font-bold text-gray-500">Training #{training.id}</h3><span className={statusClassName(training.status)}>{humanize(training.status)}</span></div><p className="text-sm text-gray-600">Client #{training.clientId} · {formatDate(training.date)} {training.startTime} · {training.durationMinutes} min · busy: {training.isBusy ? "yes" : "no"}</p><p className="text-sm text-gray-600">Payment {formatMoney(training.payment.amount, training.payment.currency)} · booked {formatDateTime(training.bookedAt)}</p></div>} getActions={(training) => [{ key: "cancel", label: "Cancel", description: "Cancel this training.", tone: "danger", run: () => adminTrainingsStore.cancel(training.id) }, { key: "complete", label: "Complete", description: "Mark this training completed.", run: () => adminTrainingsStore.complete(training.id) }]} /></AdminShell>; };
