<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260116175106 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE membership (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, status VARCHAR(7) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, client_id INT NOT NULL, plan_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_86FFD28519EB6921 ON membership (client_id)');
        $this->addSql('CREATE INDEX IDX_86FFD285E899029B ON membership (plan_id)');
        $this->addSql('ALTER TABLE membership ADD CONSTRAINT FK_86FFD28519EB6921 FOREIGN KEY (client_id) REFERENCES "client" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE membership ADD CONSTRAINT FK_86FFD285E899029B FOREIGN KEY (plan_id) REFERENCES membership_plan (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE membership DROP CONSTRAINT FK_86FFD28519EB6921');
        $this->addSql('ALTER TABLE membership DROP CONSTRAINT FK_86FFD285E899029B');
        $this->addSql('DROP TABLE membership');
    }
}
