<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260409201806 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, booked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, status VARCHAR(9) DEFAULT \'scheduled\' NOT NULL, client_id INT NOT NULL, training_id INT DEFAULT NULL, payment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E00CEDDE19EB6921 ON booking (client_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E00CEDDEBEFD98D1 ON booking (training_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E00CEDDE4C3A3BB ON booking (payment_id)');
        $this->addSql('CREATE TABLE membership (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, status VARCHAR(7) DEFAULT \'active\' NOT NULL, visits INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, frozen_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, client_id INT NOT NULL, plan_id INT DEFAULT NULL, payment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_86FFD28519EB6921 ON membership (client_id)');
        $this->addSql('CREATE INDEX IDX_86FFD285E899029B ON membership (plan_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_86FFD2854C3A3BB ON membership (payment_id)');
        $this->addSql('CREATE TABLE membership_plan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, duration_days INT NOT NULL, session_limit INT DEFAULT NULL, price NUMERIC(10, 2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_refund BOOLEAN NOT NULL, client_full_name VARCHAR(200) NOT NULL, client_email VARCHAR(180) NOT NULL, client_phone VARCHAR(20) NOT NULL, trainer_full_name VARCHAR(200) DEFAULT NULL, amount NUMERIC(10, 2) NOT NULL, category VARCHAR(10) NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, client_id INT DEFAULT NULL, trainer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D28840D19EB6921 ON payment (client_id)');
        $this->addSql('CREATE INDEX IDX_6D28840DFB08EDF6 ON payment (trainer_id)');
        $this->addSql('CREATE TABLE refresh_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(1023) NOT NULL, expires_at DATE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C74F2195A76ED395 ON refresh_token (user_id)');
        $this->addSql('CREATE TABLE trainer_work_time (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, trainer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8530A6CBFB08EDF6 ON trainer_work_time (trainer_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_trainer_day ON trainer_work_time (trainer_id, date)');
        $this->addSql('CREATE TABLE training (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, duration_minutes INT DEFAULT 60 NOT NULL, trainer_work_time_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5128A8F253F97D7 ON training (trainer_work_time_id)');
        $this->addSql('CREATE TABLE training_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT NOT NULL, photo_url VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, phone VARCHAR(20) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_blocked BOOLEAN DEFAULT false NOT NULL, blocked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, blocked_reason TEXT DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(255) NOT NULL, age INT DEFAULT NULL, balance NUMERIC(10, 2) DEFAULT NULL, price_per_hour NUMERIC(10, 2) DEFAULT NULL, photo_url VARCHAR(255) DEFAULT NULL, education VARCHAR(255) DEFAULT NULL, about VARCHAR(255) DEFAULT NULL, training_type_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D64918721C9D ON "user" (training_type_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE19EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEBEFD98D1 FOREIGN KEY (training_id) REFERENCES training (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE4C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE membership ADD CONSTRAINT FK_86FFD28519EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE membership ADD CONSTRAINT FK_86FFD285E899029B FOREIGN KEY (plan_id) REFERENCES membership_plan (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE membership ADD CONSTRAINT FK_86FFD2854C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D19EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DFB08EDF6 FOREIGN KEY (trainer_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE refresh_token ADD CONSTRAINT FK_C74F2195A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trainer_work_time ADD CONSTRAINT FK_8530A6CBFB08EDF6 FOREIGN KEY (trainer_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training ADD CONSTRAINT FK_D5128A8F253F97D7 FOREIGN KEY (trainer_work_time_id) REFERENCES trainer_work_time (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64918721C9D FOREIGN KEY (training_type_id) REFERENCES training_type (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE19EB6921');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDEBEFD98D1');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE4C3A3BB');
        $this->addSql('ALTER TABLE membership DROP CONSTRAINT FK_86FFD28519EB6921');
        $this->addSql('ALTER TABLE membership DROP CONSTRAINT FK_86FFD285E899029B');
        $this->addSql('ALTER TABLE membership DROP CONSTRAINT FK_86FFD2854C3A3BB');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D19EB6921');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840DFB08EDF6');
        $this->addSql('ALTER TABLE refresh_token DROP CONSTRAINT FK_C74F2195A76ED395');
        $this->addSql('ALTER TABLE trainer_work_time DROP CONSTRAINT FK_8530A6CBFB08EDF6');
        $this->addSql('ALTER TABLE training DROP CONSTRAINT FK_D5128A8F253F97D7');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D64918721C9D');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE membership');
        $this->addSql('DROP TABLE membership_plan');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE refresh_token');
        $this->addSql('DROP TABLE trainer_work_time');
        $this->addSql('DROP TABLE training');
        $this->addSql('DROP TABLE training_type');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
