<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260502180455 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE import_job_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, row_id INT NOT NULL, email VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, job_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3178EDA5BE04EA9 ON import_job_item (job_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_item_import_job ON import_job_item (row_id, email, job_id)');
        $this->addSql('ALTER TABLE import_job_item ADD CONSTRAINT FK_3178EDA5BE04EA9 FOREIGN KEY (job_id) REFERENCES import_job (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE import_error ADD item_id INT NOT NULL');
        $this->addSql('ALTER TABLE import_error ADD CONSTRAINT FK_B08813BF126F525E FOREIGN KEY (item_id) REFERENCES import_job_item (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B08813BF126F525E ON import_error (item_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE import_job_item DROP CONSTRAINT FK_3178EDA5BE04EA9');
        $this->addSql('DROP TABLE import_job_item');
        $this->addSql('ALTER TABLE import_error DROP CONSTRAINT FK_B08813BF126F525E');
        $this->addSql('DROP INDEX UNIQ_B08813BF126F525E');
        $this->addSql('ALTER TABLE import_error DROP item_id');
    }
}
