<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260202175051 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE trainer_availability DROP CONSTRAINT fk_91a95071fb08edf6');
        $this->addSql('DROP TABLE trainer_availability');
        $this->addSql('CREATE TABLE trainer_work_time (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week VARCHAR(9) NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, trainer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8530A6CBFB08EDF6 ON trainer_work_time (trainer_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_trainer_day ON trainer_work_time (trainer_id, day_of_week)');
        $this->addSql('ALTER TABLE trainer_work_time ADD CONSTRAINT FK_8530A6CBFB08EDF6 FOREIGN KEY (trainer_id) REFERENCES trainer (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE trainer_availability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week VARCHAR(9) NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, duration_minutes INT DEFAULT 60 NOT NULL, trainer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_91a95071fb08edf6 ON trainer_availability (trainer_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_trainer_day ON trainer_availability (trainer_id, day_of_week)');
        $this->addSql('ALTER TABLE trainer_availability ADD CONSTRAINT fk_91a95071fb08edf6 FOREIGN KEY (trainer_id) REFERENCES trainer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trainer_work_time DROP CONSTRAINT FK_8530A6CBFB08EDF6');
        $this->addSql('DROP TABLE trainer_work_time');
    }
}
