<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260416174740 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE import_error (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, payload JSON NOT NULL, error_message TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, job_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B08813BFBE04EA9 ON import_error (job_id)');
        $this->addSql('CREATE TABLE import_job (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, total INT NOT NULL, processed INT NOT NULL, failed INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE import_error ADD CONSTRAINT FK_B08813BFBE04EA9 FOREIGN KEY (job_id) REFERENCES import_job (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE import_error DROP CONSTRAINT FK_B08813BFBE04EA9');
        $this->addSql('DROP TABLE import_error');
        $this->addSql('DROP TABLE import_job');
    }
}
