fastcgi_cache_path /var/cache/nginx/fastcgi levels=1:2 keys_zone=phpcache:10m max_size=10g inactive=60m;

server {
    listen 80;
    server_name api.evogym.local;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.evogym.local;

    ssl_certificate /etc/nginx/certs/evogym.local.pem;
    ssl_certificate_key /etc/nginx/certs/evogym.local-key.pem;

    root /var/www/public;

    resolver 127.0.0.11 ipv6=off;

    set $cache_version "v1";

    set_by_lua_block $cache_group {
        local uri = ngx.var.request_uri
        local m = ngx.re.match(uri, "^/api/([^/]+)")

        if m then
            return m[1]
        end

        return "default"
    }

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        rewrite_by_lua_block {
            local redis = require "resty.redis"
            local red = redis:new()

            red:set_timeout(100)

            local ok, err = red:connect("redis", 6379)

            if not ok then
                ngx.log(ngx.ERR, "REDIS CONNECTION FAILED: ", err)
                ngx.var.cache_version = "v1"
                return
            end

            local key = "cache_version:" .. ngx.var.cache_group

            local version = red:get(key)

            if version == ngx.null then
                version = "1"
            end

            ngx.var.cache_version = "v" .. version
        }

        set $no_cache "";
        if ($http_cookie ~* "access_token") {
            set $no_cache "1";
        }

        if ($request_uri ~ ^/api/(login|refresh|logout)/) {
            set $no_cache "1";
        }

        if ($request_uri ~ ^/api/(membership/plans|trainers|trainers/[^/]+/worktime|training/types)/) {
            set $no_cache "";
        }

        fastcgi_no_cache $no_cache;
        fastcgi_cache_bypass $no_cache;

        fastcgi_cache phpcache;
        fastcgi_cache_key "$scheme$host$request_uri$cache_version";
        fastcgi_cache_valid 200 302 10m;
        fastcgi_cache_valid 404 1m;

        #fastcgi_ignore_headers Cache-Control Expires Set-Cookie;

        add_header X-FastCGI-Cache $upstream_cache_status;

        if ($no_cache = "") {
            add_header X-FastCGI-Cache-Key "$scheme$host$request_uri$cache_version";
            add_header X-FastCGI-Cache-Group $cache_group;
            add_header X-FastCGI-Cache-Version $cache_version;
        }

        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        fastcgi_param PHP_IDE_CONFIG "serverName=docker-cli";
        fastcgi_param XDEBUG_SESSION "PHPSTORM";
    }

    location ~ \.php$ {
        return 404;
    }
}

server {
    listen 80;
    server_name evogym.local;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name evogym.local;

    ssl_certificate /etc/nginx/certs/evogym.local.pem;
    ssl_certificate_key /etc/nginx/certs/evogym.local-key.pem;

    resolver 127.0.0.11 ipv6=off;

    location / {
        proxy_pass http://frontend:3000;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}