<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260206114851 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, booked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, status VARCHAR(9) DEFAULT \'scheduled\' NOT NULL, client_id INT NOT NULL, training_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E00CEDDE19EB6921 ON booking (client_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E00CEDDEBEFD98D1 ON booking (training_id)');
        $this->addSql('CREATE TABLE "client" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, age INT NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, password VARCHAR(255) NOT NULL, balance NUMERIC(10, 2) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C7440455E7927C74 ON "client" (email)');
        $this->addSql('CREATE TABLE membership (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, status VARCHAR(7) DEFAULT \'active\' NOT NULL, visits INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, client_id INT NOT NULL, plan_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_86FFD28519EB6921 ON membership (client_id)');
        $this->addSql('CREATE INDEX IDX_86FFD285E899029B ON membership (plan_id)');
        $this->addSql('CREATE TABLE membership_plan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, duration_days INT NOT NULL, session_limit INT DEFAULT NULL, price NUMERIC(10, 2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(10, 2) NOT NULL, category VARCHAR(10) NOT NULL, status VARCHAR(9) DEFAULT \'pending\' NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, client_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D28840D19EB6921 ON payment (client_id)');
        $this->addSql('CREATE TABLE trainer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(20) NOT NULL, price NUMERIC(10, 2) NOT NULL, training_type_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C515082018721C9D ON trainer (training_type_id)');
        $this->addSql('CREATE TABLE trainer_work_time (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, trainer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8530A6CBFB08EDF6 ON trainer_work_time (trainer_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_trainer_day ON trainer_work_time (trainer_id, date)');
        $this->addSql('CREATE TABLE training (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, duration_minutes INT DEFAULT 60 NOT NULL, trainer_work_time_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5128A8F253F97D7 ON training (trainer_work_time_id)');
        $this->addSql('CREATE TABLE training_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE19EB6921 FOREIGN KEY (client_id) REFERENCES "client" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEBEFD98D1 FOREIGN KEY (training_id) REFERENCES training (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE membership ADD CONSTRAINT FK_86FFD28519EB6921 FOREIGN KEY (client_id) REFERENCES "client" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE membership ADD CONSTRAINT FK_86FFD285E899029B FOREIGN KEY (plan_id) REFERENCES membership_plan (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D19EB6921 FOREIGN KEY (client_id) REFERENCES "client" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trainer ADD CONSTRAINT FK_C515082018721C9D FOREIGN KEY (training_type_id) REFERENCES training_type (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trainer_work_time ADD CONSTRAINT FK_8530A6CBFB08EDF6 FOREIGN KEY (trainer_id) REFERENCES trainer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training ADD CONSTRAINT FK_D5128A8F253F97D7 FOREIGN KEY (trainer_work_time_id) REFERENCES trainer_work_time (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE19EB6921');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDEBEFD98D1');
        $this->addSql('ALTER TABLE membership DROP CONSTRAINT FK_86FFD28519EB6921');
        $this->addSql('ALTER TABLE membership DROP CONSTRAINT FK_86FFD285E899029B');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D19EB6921');
        $this->addSql('ALTER TABLE trainer DROP CONSTRAINT FK_C515082018721C9D');
        $this->addSql('ALTER TABLE trainer_work_time DROP CONSTRAINT FK_8530A6CBFB08EDF6');
        $this->addSql('ALTER TABLE training DROP CONSTRAINT FK_D5128A8F253F97D7');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE "client"');
        $this->addSql('DROP TABLE membership');
        $this->addSql('DROP TABLE membership_plan');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE trainer');
        $this->addSql('DROP TABLE trainer_work_time');
        $this->addSql('DROP TABLE training');
        $this->addSql('DROP TABLE training_type');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
